import { z } from 'zod';

export const PermissionCode = z.enum([
  'MARK_STUDENT_ATTENDANCE',
  'MARK_TEACHER_ATTENDANCE',
  'MARK_STAFF_ATTENDANCE',
  'VIEW_ATTENDANCE_REPORTS',
  'MANAGE_CLASSES',
  'MANAGE_SUBJECTS',
  'INPUT_GRADES',
  'PUBLISH_BULLETINS',
  'CREATE_USER',
  'UPDATE_USER',
  'DELETE_USER',
  'MANAGE_USER_PERMISSIONS',
  'MANAGE_PAYMENTS',
  'VIEW_FINANCIAL_REPORTS',
]);
