services:
  service-auth:
    build:
      context: .
      dockerfile: infra/docker/service-auth.dockerfile
    container_name: stackschool-service-auth
    environment:
      DATABASE_URL: postgresql://${POSTGRES_AUTH_USER}:${POSTGRES_AUTH_PASSWORD}@auth_db:5432/${POSTGRES_AUTH_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      GATEWAY_INTERNAL_SECRET: ${GATEWAY_INTERNAL_SECRET}
      REDIS_URL: redis://redis:6379
    expose:
      - '4001'
    depends_on:
      auth_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - stackschool-net

  service-core:
    build:
      context: .
      dockerfile: infra/docker/service-core.dockerfile
    container_name: stackschool-service-core
    environment:
      DATABASE_URL: postgresql://${POSTGRES_CORE_USER}:${POSTGRES_CORE_PASSWORD}@core_db:5432/${POSTGRES_CORE_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      GATEWAY_INTERNAL_SECRET: ${GATEWAY_INTERNAL_SECRET}
    expose:
      - '4002'
    depends_on:
      core_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - stackschool-net

  service-academic:
    build:
      context: .
      dockerfile: infra/docker/service-academic.dockerfile
    container_name: stackschool-service-academic
    environment:
      DATABASE_URL: postgresql://${POSTGRES_ACADEMIC_USER}:${POSTGRES_ACADEMIC_PASSWORD}@academic_db:5432/${POSTGRES_ACADEMIC_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      GATEWAY_INTERNAL_SECRET: ${GATEWAY_INTERNAL_SECRET}
    expose:
      - '4003'
    depends_on:
      academic_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - stackschool-net

  service-operations:
    build:
      context: .
      dockerfile: infra/docker/service-operations.dockerfile
    container_name: stackschool-service-operations
    environment:
      DATABASE_URL: postgresql://${POSTGRES_OPERATIONS_USER}:${POSTGRES_OPERATIONS_PASSWORD}@operations_db:5432/${POSTGRES_OPERATIONS_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      GATEWAY_INTERNAL_SECRET: ${GATEWAY_INTERNAL_SECRET}
    expose:
      - '4004'
    depends_on:
      operations_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - stackschool-net

  gateway:
    build:
      context: .
      dockerfile: infra/docker/gateway.dockerfile
    container_name: stackschool-gateway
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      REDIS_URL: redis://redis:6379
      GATEWAY_INTERNAL_SECRET: ${GATEWAY_INTERNAL_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - '4000:4000' # seul service exposé publiquement
    depends_on:
      service-auth:
        condition: service_started
      service-core:
        condition: service_started
      service-academic:
        condition: service_started
      service-operations:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - stackschool-net

  auth_db:
    image: postgres:17
    container_name: stackschool-auth
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - stackschool-net

  core_db:
    image: postgres:17
    container_name: stackschool-core
    environment:
      POSTGRES_USER: ${POSTGRES_CORE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CORE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CORE_DB}
    volumes:
      - core_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - stackschool-net

  operations_db:
    image: postgres:17
    container_name: stackschool-operations
    environment:
      POSTGRES_USER: ${POSTGRES_OPERATIONS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_OPERATIONS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_OPERATIONS_DB}
    volumes:
      - operations_data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
    networks:
      - stackschool-net

  academic_db:
    image: postgres:17
    container_name: stackschool-academic
    environment:
      POSTGRES_USER: ${POSTGRES_ACADEMIC_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ACADEMIC_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ACADEMIC_DB}
    volumes:
      - academic_data:/var/lib/postgresql/data
    ports:
      - '5437:5432'
    networks:
      - stackschool-net

  redis:
    image: redis:7
    container_name: stackschool-redis
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - stackschool-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: stackschool-rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_port_connectivity']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # UI management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - stackschool-net

  minio:
    image: minio/minio:latest
    container_name: stackschool-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'   # API S3
      - '9001:9001'   # Console admin
    networks:
      - stackschool-net

volumes:
  db_data:
  auth_data:
  core_data:
  operations_data:
  academic_data:
  redis_data:
  rabbitmq_data:
  minio_data:

networks:
  stackschool-net:
    driver: bridge
