packages:
  - 'packages/messaging'
  - 'packages/contracts'
  - 'packages/ui'
  - 'apps/gateway'
  - 'apps/web'
  - 'apps/service-auth'
  - 'apps/service-core'
  - 'apps/service-operations'
  - 'apps/service-academic'

allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  '@prisma/client': true
  msgpackr-extract: true
  nx: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  '@swc/core': true
  ngrok: false

catalog:
  react: '^19.2.3'
  react-dom: '^19.2.3'
  '@types/react': '^19.2.3'
  '@types/react-dom': '^19.2.3'
  '@prisma/client': '7.8.0'
  'prisma': '7.8.0'
  '@prisma/adapter-pg': '7.8.0'
  zod: '^4.4.3'

overrides:
  react: 'catalog:'
  react-dom: 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  lightningcss: 1.30.1
  '@prisma/client': 'catalog:'
  prisma: 'catalog:'
  '@prisma/adapter-pg': 'catalog:'
  zod: 'catalog:'

publicHoistPattern:
  - '*eslint*'
  - '*babel*'
  - '@swc/cli'
  - '@swc/core'
  - 'tsup'
  - '*microservices*'
  - '*tanstack*'
  - '*zod*'
  - '*dotenv*'
  - '*typescript*'
  - '*node*'
  - '*nestjs*'
  - '*react*'
  - '*axios*'
  - '*react-hook-form*'
  - '*jest*'
  - '*date-fns*'
  - '*type*'
