POST  http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Content-Type: application/json; charset=utf-8
Set-Cookie: refresh_token=df1527beee1ce905f751a5b77912e0a2; Max-Age=2159999; Path=/; Expires=Thu, 30 Jul 2026 09:39:40 GMT; HttpOnly; SameSite=Lax,sid=s%3AJ3kwn6nzvbkxO6dbGXf445fYwTuoueKD.JQichS4oAyKJYFT570QMevobo4BlGSMGVOHfG5uPMsg; Path=/; Expires=Sun, 05 Jul 2026 10:09:40 GMT; HttpOnly; SameSite=Lax

 query Me {
  me {
    id 
    email
    username
    profile {
      firstname
      lastname
      photo
    }
    memberships {
      id 
      role
    }
  }
 }
  
