FROM node:lts-slim

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-workspace.yaml* ./

COPY packages/db ./packages/db
COPY packages/shared ./packages/shared
COPY apps/api ./apps/api

RUN pnpm install --no-frozen-lockfile

EXPOSE 4000 51212
 
# Solution simple et fiable
WORKDIR /app/apps/api
CMD ["pnpm", "run", "dev"]