FROM node:20-slim
WORKDIR /app

COPY ../../backend/package.json backend/package-lock.json* ./
RUN npm install

COPY ../../backend ./

ENV NODE_ENV=development
EXPOSE 4000
CMD ["npm", "run", "dev"]




