# Dockerfile
ARG APP_NAME

FROM node:lts-slim AS base
RUN npm install -g pnpm@11.9.0 nx
WORKDIR /repo

# --- Étape 1 : install + build ---
FROM base AS builder
ARG APP_NAME

COPY pnpm-workspace.yaml package.json tsconfig.base.json ./
COPY apps ./apps
COPY packages/contracts ./packages/contracts
COPY packages/messaging ./packages/messaging

RUN pnpm install --frozen-lockfile

# Génère les clients Prisma nécessaires (seulement ceux référencés par le build)
RUN pnpm --filter "./packages/db-*" exec prisma generate

RUN npx nx build ${APP_NAME}

# --- Étape 2 : image finale ---
FROM node:lts-slim AS runner
ARG APP_NAME
ENV NODE_ENV=production
WORKDIR /repo

COPY --from=builder /repo/node_modules ./node_modules
COPY --from=builder /repo/apps ./apps
COPY --from=builder /repo/packages/messaging ./packages/messaging
COPY --from=builder /repo/packages/contracts ./packages/contracts
COPY --from=builder /repo/package.json ./package.json

ENV APP_ENTRY=apps/${APP_NAME}/dist/main.js
CMD ["sh", "-c", "node $APP_ENTRY"]