# --- Development image ---
FROM node:lts-slim

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-workspace.yaml ./

COPY packages/shared ./packages/shared
COPY packages/db ./packages/db
COPY packages/ui ./packages/ui

COPY apps/web ./apps/web

RUN pnpm install  --no-frozen-lockfile

EXPOSE 3000


# ... autres instructions ...
CMD ["pnpm", "--workspace-root", "--filter", "@stackschool/web", "run", "dev"]
