import { type Theme } from '@react-navigation/native';
export declare const THEME: {
    light: {
        background: string;
        foreground: string;
        card: string;
        cardForeground: string;
        popover: string;
        popoverForeground: string;
        primary: string;
        primaryForeground: string;
        secondary: string;
        secondaryForeground: string;
        muted: string;
        mutedForeground: string;
        accent: string;
        accentForeground: string;
        destructive: string;
        border: string;
        input: string;
        ring: string;
        radius: string;
        chart1: string;
        chart2: string;
        chart3: string;
        chart4: string;
        chart5: string;
    };
    dark: {
        background: string;
        foreground: string;
        card: string;
        cardForeground: string;
        popover: string;
        popoverForeground: string;
        primary: string;
        primaryForeground: string;
        secondary: string;
        secondaryForeground: string;
        muted: string;
        mutedForeground: string;
        accent: string;
        accentForeground: string;
        destructive: string;
        border: string;
        input: string;
        ring: string;
        radius: string;
        chart1: string;
        chart2: string;
        chart3: string;
        chart4: string;
        chart5: string;
    };
};
export declare const NAV_THEME: Record<'light' | 'dark', Theme>;
//# sourceMappingURL=theme.d.ts.map