type Student @key(fields: "id") {
  id: ID!
  matricule: String!
  birthDate: DateTime
  birthPlace: DateTime
  schoolUserId: ID
  enrollmentDate: DateTime
  previousClass: String
  studentNumber: Int
  bloodGroup: String
  birthCertificateNumber: String
  medicalCondition: String
  allergies: String
  #attendances(date: Date): [AttendanceRecord!]
  transportMode: TransportMode
  previousSchool: String
  classId: ID! @shareable
  enrollmentYear: String
  status: StudentStatus
  disciplinaryActions: StudentDisciplinaryAction
  nationality: String
  profileId: ID
  parentStudent: [ParentStudent]
  schoolProfile: SchoolProfile
  schoolUser: SchoolMembership
}

input GetSchoolStudentsInput {
  page: Int! = 0
  limit: Int! = 10
  teacherId: String
  sort: StudentSortInput
  classId: ID
  searchTerm: String
  level: String
  section: String
}

input StudentSortInput {
  field: StudentSortField
  order: SortOrder
}
input CreateStudentInput {
  firstName: String!
  lastName: String!
  email: String
  phoneNumber: String
  gender: Gender!
  classId: ID!
  matricule: String!
  birthDate: DateTime
  birthPlace: String
  enrollmentYear: String
  nationality: String
  enrollmentDate: DateTime
  previousClass: String
  studentNumber: Int
  address: String
  bloodGroup: String
  birthCertificateNumber: String
  medicalCondition: String
  allergies: String
  parentData: UpdateStudentParentData
  transportMode: TransportMode
  previousSchool: String
  status: StudentStatus
}

type StudentDisciplinaryAction {
  id: String
  studentId: ID
  type: DisciplinaryType
  reason: String
  startDate: DateTime
  endDate: DateTime
}

type StudentList {
  data: [Student!]
  meta: PaginationMeta!
}

input StudentSearchInput {
  schoolId: ID
  searchTerm: String
  getSubject: Boolean
  limit: Int
}
