type Teacher @key(fields: "id") {
  id: ID!
  schoolUserId: ID
  diploma: String
  experience: String
  hireDate: DateTime
  isActive: Boolean
  bio: String
  salary: Float
  department: String
  specialization: String
  createdAt: DateTime
  updatedAt: DateTime
  #attendances(date: Date): [AttendanceRecord!]
  weeklyHours: Float
  classesCount: Int
  schoolUser: SchoolMembership
  schoolProfile: SchoolProfile
}

input CreateTeacherInput {
  firstName: String!
  lastName: String!
  email: String
  phoneNumber: String
  gender: Gender!
  diploma: String
  specialization: String!
}
type TeacherList {
  data: [Teacher!]!
  meta: PaginationMeta!
}

input GetSchoolTeachersInput {
  page: Int! = 0
  limit: Int! = 10
  searchTerm: String
  classId: ID
  subjectId: ID
  isActive: Boolean
  isSupervisor: Boolean
  day: Day
}

type TeacherTodaySubject {
  teachers: Teacher
  # classes: ClassLessons
}
