enum RelationType {
  FATHER
  MOTHER
  GUARDIAN
  UNCLE
  OTHER
  GRAND_MOTHER
  GRAND_FATHER
  AUNT
}

enum Day {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}
enum TransportMode {
  BUS
  WALK
  CAR
  MOTO
  TAXI
  PARENT
  OTHER
}

enum SchoolRole {
  ADMIN
  TEACHER
  STUDENT
  PARENT
  STAFF
}

enum StudentStatus {
  ACTIVE
  SUSPENDED
  EXPELLED
  TRANSFERRED
  DROPPED_OUT
  GRADUATED
  INACTIVE
  DECEASED
}
enum SortOrder {
  ASC
  DESC
}
enum StudentSortField {
  firstname
  lastname
  enrolementYear
}

enum PermissionCode {
  MARK_STUDENT_ATTENDANCE
  MARK_TEACHER_ATTENDANCE
  MARK_STAFF_ATTENDANCE
  VIEW_ATTENDANCE_REPORTS

  MANAGE_SUBJECTS
  INPUT_GRADES
  PUBLISH_BULLETINS

  CREATE_USER
  UPDATE_USER
  DELETE_USER
  MANAGE_USER_PERMISSIONS

  MANAGE_PAYMENTS
  VIEW_FINANCIAL_REPORTS
}

enum PermissionModule {
  ATTENDANCE
  ACADEMICS
  USERS
  FINANCE
  SETTINGS
}
