type Mutation {
  createTeacher(input: CreateTeacherInput): Teacher
  createTeacherAssignment(input: CreateTeacherAssignmentInput!): ApiResponse
  syncTeacherAssignment(input: CreateTeacherAssignmentInput!): ApiResponse
  deleteTeacherAssignment(id: ID!, subjectIds: [ID!]): ApiResponse
  updateTeacher(teacherId: ID!, data: CreateTeacherInput!): Teacher
  deleteTeachers(teacherIds: [ID!]!, soft: Boolean = true): ApiResponse
  deleteStudents(
    studentIds: [ID!]!
    schoolId: ID!
    soft: Boolean = true
  ): ApiResponse
  createListStudent(data: CreateStudentInput!, schoolId: ID!): ApiResponse
  updateStudent(
    studentId: ID!
    data: CreateStudentInput!
    schoolId: ID!
  ): Student
  createParent(input: CreateParentInput!): Parent!
}
