type Parent {
  id: ID!
  profession: String
  isDelegate: Boolean
  parentStudent: [ParentStudent]
  schoolUserId: ID
  user: User
}

type ParentStudent {
  relationType: RelationType
  student: Student
  studentId: ID
  parentId: ID
  parent: Parent
}

input CreateParentInput {
  firstName: String!
  lastName: String!
  phoneNumber: String!
  isDelegate: Boolean
  email: String
  address: String!
  profession: String!
  children: [ParentStudentInput!]
}
input UpdateStudentParentData {
  mode: ParentStudentUpdateMode
  parentId: ID
  newParent: CreateParentInput
}
input ParentStudentInput {
  id: ID!
  relationType: RelationType!
}

input GetSchoolParentsInput {
  page: Int! = 0
  limit: Int! = 10
  searchTerm: String
  studentId: String
}
type ParentList {
  data: [Parent!]
  meta: PaginationMeta
}
