extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.3"
    import: ["@key", "@shareable"]
  )
scalar DateTime
scalar Date

type School @key(fields: "id") {
  id: ID!
  name: String!
  slug: String
  address: String!
  code: String
  logo: String
  stats: SchoolStats
  settings: SchoolSettings
  teachers: [Teacher]
  lessons: [Lesson]
}

type SchoolSettings @key(fields: "id") {
  id: ID!
  schoolId: ID
  lessonDuration: Int
  startHour: Int
  endHour: Int
  daysOfWeek: [Day]
}

type SchoolStats {
  # KPI Cards
  totalStudents: Int!
  totalTeachers: Int!
  totalClasses: Int!

  # Finance & Présence
  monthlyRevenue: MonthlyRevenue
  pendingPaymentsCount: Int

  # Remplacé par un objet complexe
  # attendance: AttendanceStats

  # Charts Data
  studentGender: GenderStats
  # enrollmentPerMonth: [MonthlyStats!]
  # classesOccupancy: [ClassStats!]
}

type MonthlyRevenue {
  currentMonth: Float!
  previousMonth: Float
}

type GenderStats {
  male: Int!
  female: Int!
}
