type Subject @key(fields: "id") {
  id: ID!
  name: String!
  code: String
  category: SubjectCategory
  totalWeeklyHours: Float
  mainTeacherId: ID
  classSubject: [ClassSubject]
}
input GetSubjectInput {
  page: Int! = 0
  limit: Int! = 10
  searchTerm: String
  classId: ID
  teacherId: ID
}
input CreateSubjectInput {
  name: String!
  code: String!
  mainTeacherId: ID
  category: SubjectCategory!
  classSubject: [ClassSubjectInput!]
}
type SubjectList {
  data: [Subject!]!
  meta: PaginationMeta!
}
