import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import Header from "@/components/Header";
import { ModeToggle } from "@/components/DropMenu";
import { prisma } from "../lib/prisma";
import { Toaster } from "@/components/ui/sonner";
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" enableSystem={false}>
          {children}
          <Toaster
            position="top-center"
            className="bg-sky-500! text-lg"
            duration={4000}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
