"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const refresh_route_1 = __importDefault(require("./refresh.route"));
const me_route_1 = __importDefault(require("./me.route"));
const logout_route_1 = __importDefault(require("./logout.route"));
const passport_google_route_1 = __importDefault(require("./passport-google.route"));
const login_route_1 = __importDefault(require("./login.route"));
const register_route_1 = __importDefault(require("./register.route"));
const verify_code_route_1 = __importDefault(require("./verify-code.route"));
const passport_facebook_route_1 = __importDefault(require("./passport-facebook.route"));
const resend_code_route_1 = __importDefault(require("./resend-code.route"));
const reset_password_route_1 = __importDefault(require("./reset-password.route"));
const google_post_route_1 = __importDefault(require("./google-post.route"));
const facebook_post_route_1 = __importDefault(require("./facebook-post.route"));
const express_1 = require("express");
const router = (0, express_1.Router)();
router.use('/auth', refresh_route_1.default);
router.use('/auth', me_route_1.default);
router.use('/auth', logout_route_1.default);
router.use('/auth', passport_google_route_1.default);
router.use('/auth', login_route_1.default);
router.use('/auth', register_route_1.default);
router.use('/auth', verify_code_route_1.default);
router.use('/auth', passport_facebook_route_1.default);
router.use('/auth', resend_code_route_1.default);
router.use('/auth', reset_password_route_1.default);
router.use('/auth', google_post_route_1.default);
router.use('/auth', facebook_post_route_1.default);
exports.default = router;
//# sourceMappingURL=index.js.map