type Lesson @key(fields: "id teacherId") {
  id: ID!
  title: String
  startTime: DateTime
  endTime: DateTime
  day: Day
  teacherAssignmentId: ID
  teacherAssignment: TeacherAssignment
  status: LessonStatus!
  teacherId: ID
  resourceId: ID
  mode: ResourceMode
  room: Room
  group: Group
  subject: Subject
}

input CreateLessonInput {
  day: Day!
  mode: ResourceMode!
  startTime: DateTime!
  endTime: DateTime!
  subjectId: ID!
  teacherId: ID
  groupId: ID
  roomId: ID
  title: String
}

input UpdateLessonInput {
  id: ID!
  startTime: DateTime
  endTime: DateTime
  day: Day
  mode: ResourceMode
}

input GetLessonsInput {
  groupId: ID
  teacherId: ID
  classId: ID
  department: String
  mode: ResourceMode!
  hasLessonOnly: Boolean = true
  section: String
  status: LessonStatus
  level: String
  limit: Int! = 6
  page: Int! = 0
}

type LessonsData {
  events: [Lesson!]
  resources: [LessonResources!]
}

type LessonResources {
  id: ID!
  title: String!
  weeklyHours: Int
}

type LessonsList {
  data: LessonsData!
  meta: PaginationMeta
}

type Subject @key(fields: "id") {
  id: ID!
}

type Room @key(fields: "id") {
  id: ID!
}
