type ClassList {
  data: [Class!]
  meta: PaginationMeta!
}
type ClassCount {
  students: GenderStats
  teachers: Int
  subjects: Int
}
type ClassStats {
  className: String!
  studentCount: Int!
}
input CreateClassInput {
  section: String
  name: String!
  level: String!
  supervisorId: String
}
input GetSchoolClassesInput {
  page: Int! = 0
  limit: Int! = 10
  level: String
  section: String
  teacherId: String
  searchTerm: String
}
type ClassLessons {
  classSubject: ClassSubject
  lesson: Lesson
}
